paperless:
  admin:
    username: admin
    email: info@example.com
  replicaCount: 1
  image:
    repository: paperlessngx/paperless-ngx
    tag: 2.19.2
    pullPolicy: IfNotPresent
  allowSignups: "false"
  ingress:
    host: paperless.example.com
    className: "traefik"
    annotations: {}

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "6.2-alpine"
    pullPolicy: IfNotPresent

postgresql:
  image:
    repository: postgres
    tag: "18.0-alpine3.22"
    pullPolicy: IfNotPresent
  auth:
    username: paperless
    password: paperlesspassword

gotenberg:
  image:
    repository: gotenberg/gotenberg
    tag: "8.24.0"

tika:
  image:
    repository: apache/tika
    tag: "3.2.3.0-full"

n8n:
  image:
    repository: n8nio/n8n
    tag: "1.123.1"
  ingress:
    host: n8n.example.com
    className: "traefik"
    annotations: {}
  postgresql:
    image:
      repository: postgres
      tag: "18.0-alpine3.22"
      pullPolicy: IfNotPresent
    auth:
      username: n8n
      password: n8npassword
  licenseKey: "6ebe7cac-6817-4f79-8b7d-650da08118da"