apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-paperless
spec:
  selector:
    app: {{ .Chart.Name }}-paperless
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis
spec:
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-paperless-postgresql
spec:
  selector:
    app: {{ .Chart.Name }}-paperless-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-gotenberg
spec:
  selector:
    app: {{ .Chart.Name }}-gotenberg
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-tika
spec:
  selector:
    app: {{ .Chart.Name }}-tika
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-n8n-postgresql
spec:
  selector:
    app: {{ .Chart.Name }}-n8n-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-n8n
spec:
  selector:
    app: {{ .Chart.Name }}-n8n
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-samba
spec:
  selector:
    app: {{ .Chart.Name }}-samba
  ports:
    - protocol: TCP
      port: 445
      targetPort: 445
  type: LoadBalancer
---